import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Topbar from '../Components/Topbar/Topbar'
import { motion } from 'framer-motion'
import prismaclient from '../utils/prismaclient'
import { Plus, Minus, ArrowRight, Filter } from 'react-feather'
import axios from 'axios'

import FilterBar from '../Components/FilterBar/FilterBar'
import Footer from '../Components/Footer/Footer'
import SingleProduct from '../Components/Product/SingleProduct'
import BottomNavigation from '../Components/BottomNavigation/BottomNavigation'

export async function getServerSideProps({ req, res }) {
    if (typeof window === 'undefined') {
        let products = await prismaclient.product.findMany()
        let brands = await prismaclient.brand.findMany()

        let token = req.cookies.token || ''

        if (token !== '') {
            let response = await axios.get(
                `https://jaysneakers.herokuapp.com/api/auth/verify`,
                {
                    headers: {
                        authorization: token,
                    },
                }
            )

            if (response.data.status === 200) {
                return {
                    props: {
                        products: JSON.parse(JSON.stringify(products)),
                        brands: JSON.parse(JSON.stringify(brands)),
                        user: response.data.data,
                    },
                }
            }
        }

        return {
            props: {
                products: JSON.parse(JSON.stringify(products)),
                brands: JSON.parse(JSON.stringify(brands)),
            },
        }
    }
}

export default function Home({ products, brands, user }) {
    const [allProducts, setAllProducts] = useState(products)
    const [toggleFilter, setToggleFilter] = useState(false)

    const filterOnBrand = (brand) => {
        setAllProducts((prev) => {
            let newList = prev.filter((prevItem) => prevItem.bid === brand)

            return newList
        })
    }

    const filterByCollection = (collection) => {
        console.log(collection)
        setAllProducts((prev) => {
            if (collection === 'all') {
                return products
            }

            let newList = prev.filter(
                (prevItem) => prevItem.category === collection
            )

            return newList
        })
    }

    const filterBySize = (size) => {
        setAllProducts((prev) => {
            let newList = prev.filter((prevItem) =>
                prevItem.sizes.includes(size.toString())
            )

            return newList
        })
    }

    const returnSearchResult = (keyword) => {
        setAllProducts((prev) => {
            if (keyword.length && keyword !== '') {
                let newList = prev.filter((prevItem) =>
                    prevItem.title.toLowerCase().includes(keyword.toLowerCase())
                )

                return newList
            } else {
                return products
            }
        })
    }

    return (
        <motion.div exit={{ opacity: 0 }}>
            <Head>
                <title>Jays. | Best Sneakers for everyone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
                <link rel='preconnect' href='https://fonts.gstatic.com' />
                <link
                    href='https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap'
                    rel='stylesheet'
                />
            </Head>
            <Topbar user={user || {}} getSearchKey={returnSearchResult} />
            <motion.div
                className='hero'
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.65 }}>
                <div className='container'>
                    <div className='row'>
                        <div className='col-12 col-lg-6 mobile-order-2'>
                            <div className='description'>
                                <motion.h1
                                    initial={{ opacity: 0, x: -50 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: 0.8 }}>
                                    Feel light as a <br /> Feather.
                                </motion.h1>
                                <h3 className='my-3'>Adidas White Sneaker</h3>
                                <h4 className='fw-bold'>$45</h4>
                                <div className='d-flex align-items-center justify-content-start mt-3'>
                                    <button className='btn btn-primary'>
                                        Add To Cart
                                    </button>
                                    <div className='quantity'>
                                        <button className='btn'>
                                            <Minus size={24} />
                                        </button>
                                        <h4>1</h4>
                                        <button className='btn'>
                                            <Plus size={24} />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col-12 col-md-6 mobile-order-1'>
                            <motion.div
                                className='photo-section'
                                initial={{ opacity: 0, scale: 0.7 }}
                                animate={{ opacity: 1, scale: 1 }}
                                transition={{ delay: 1, duration: 0.6 }}>
                                <Image
                                    src='/static/images/Addidas.png'
                                    alt='Addidas Sneaker'
                                    width='700px'
                                    height='537px'
                                    priority
                                />
                                <div className='circle first'></div>
                                <div className='circle second'></div>
                            </motion.div>
                        </div>
                    </div>
                </div>
            </motion.div>
            <div className='container'>
                <h2 className='fw-bold text-left collections-title'>
                    Sneakers for Everyone
                </h2>
                <div className='row'>
                    <div className='col-12 col-lg-6'>
                        <div className='collection'>
                            <img
                                src='/static/images/forwomen.jpg'
                                alt='Women Collection'
                                width='100%'
                                height='400px'
                            />
                            <h2>For Women</h2>
                            <Link href='/collection/women'>
                                <a>
                                    Check Collection
                                    <ArrowRight size={24} className='ms-2' />
                                </a>
                            </Link>
                            <div className='overlay' />
                        </div>
                    </div>
                    <div className='col-12 col-lg-6'>
                        <div className='collection'>
                            <img
                                src='/static/images/formen.jpg'
                                alt='Men Collection'
                                width='100%'
                                height='400px'
                            />
                            <h2>For Men</h2>
                            <Link href='/collection/men'>
                                <a>
                                    Check Collection
                                    <ArrowRight size={24} className='ms-2' />
                                </a>
                            </Link>
                            <div className='overlay' />
                        </div>
                    </div>
                </div>
                <div className='row products-section'>
                    <button
                        className='btn btn-secondary filter-toggle'
                        onClick={() => setToggleFilter((prev) => !prev)}>
                        <Filter size={24} />
                    </button>
                    <div
                        className={`col-3 filter-sidebar ${
                            toggleFilter ? 'show' : ''
                        }`}>
                        <FilterBar
                            brands={brands}
                            filterBrand={filterOnBrand}
                            filterCollection={filterByCollection}
                            filterSize={filterBySize}
                        />
                    </div>
                    <div className='col-12 col-lg-9'>
                        <h2 className='fw-bold mb-3'>All Products</h2>
                        <div className='products-grid'>
                            {allProducts.length
                                ? allProducts.map((product) => (
                                      <SingleProduct
                                          product={product}
                                          key={product.id}
                                      />
                                  ))
                                : null}
                        </div>
                    </div>
                </div>
            </div>
            <BottomNavigation active={'home'} user={user} />
            <Footer />
        </motion.div>
    )
}
